/**
 * ============================================================
 * workspace-researcher/index.js — Workspace Researcher Agent
 * ============================================================
 *
 * PURPOSE:
 * Main entry point for the Workspace Researcher Agent. Tests indicate
 * whether to use mock data (--dry-run) or the real LLM models to 
 * query Google Workspace based on instructions from the Orchestrator AI.
 * 
 * DESCRIPTION:
 * Exposes a simple asynchronous API to query Workspace data contextually.
 * The orchestrator sends a text query, and this agent utilizes its own
 * Gemini instance with function calling capability to fetch the data.
 * 
 * USE CASES:
 * - "Find the latest email thread with John about Project X."
 * - "Summarize the 'Q3 OKR' document from Drive."
 * - "What meetings do I have tomorrow?"
 * ============================================================
 */

'use strict';

const { runWorkspaceResearch } = require('./agent');

/**
 * processResearchRequest
 * Main entry point called by the Orchestrator AI.
 * 
 * @param {string} query - The exact research prompt / question generated by Orchestrator
 * @returns {Promise<string>} String response in Markdown format parsing the facts.
 */
async function processResearchRequest(query) {
  try {
    console.log(`[workspace-researcher] Processing query: "${query}"`);
    const result = await runWorkspaceResearch(query);
    return result;
  } catch (error) {
    console.error(`[workspace-researcher] Error processing request:`, error);
    return `---
[STATUT] : ÉCHEC

[NOTES_DE_RECHERCHE]
Erreur inattendue lors de la recherche: ${error.message}
---`;
  }
}

module.exports = {
  processResearchRequest
};
